/**
 * @file LRPresentationTuning.h
 * @brief 定义 LostRunic 的内容数据和调优 DataAsset。设计文档中的速度、距离、角度、持续时间、冷却及表现强度都由这里提供编辑器权威值，C++ 默认值仅作安全回退。
 *
 * 关联文件：LRPresentationTuning.cpp；所属领域：Data。
 * 设计依据：Docs/Technical/08_ArchitectureBoundaries.md。
 * 除带 EditDefaultsOnly、EditAnywhere 或 EditInstanceOnly 的字段外，其余成员均为运行时状态，不应由蓝图直接改写。
 */
#pragma once

#include "Data/LRTuningAsset.h"

#include "LRPresentationTuning.generated.h"

class UMaterialInterface;
class UMaterialParameterCollection;
class UNiagaraSystem;

/** Style parameters used by the state eye overlay. The widget owns animation; this only owns authored appearance. */
USTRUCT(BlueprintType, meta = (DisplayName = "Lost Runic State Eye Overlay Style"))
struct LOSTRUNIC_API FLRStateEyeOverlayStyle
{
	GENERATED_BODY()

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Overlay")
	FLinearColor Tint = FLinearColor::Black;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Overlay", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float MaxOpacity = 0.8f;
};

/** 该公开类型定义本文件领域边界的数据或行为；具体字段、参数与约束见下方中文注释。 */
UCLASS(BlueprintType, meta = (DisplayName = "Lost Runic Presentation Tuning"))
class LOSTRUNIC_API ULRPresentationTuning : public ULRTuningAsset
{
	GENERATED_BODY()

public:
	/** Perception Reveal Radius 的空间距离参数，默认使用 Unreal 厘米单位。 C++ 安全默认值为 `450.0f`。 可在 DataAsset 或蓝图类默认值中配置，运行时蓝图只读。编辑器约束：单位 `cm`，最小值 `0.0`，最大值 `5000.0`。 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "5000.0", Units = "cm"))
	float PerceptionRevealRadius = 450.0f;

	/** Noise Reveal Radius 的空间距离参数，默认使用 Unreal 厘米单位。 C++ 安全默认值为 `200.0f`。 可在 DataAsset 或蓝图类默认值中配置，运行时蓝图只读。编辑器约束：单位 `cm`，最小值 `0.0`，最大值 `5000.0`。 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "5000.0", Units = "cm"))
	float NoiseRevealRadius = 200.0f;

	/** Noise Reveal Duration Seconds 的时间参数，单位为秒；由所属调优或资产提供权威值。 C++ 安全默认值为 `5.0f`。 可在 DataAsset 或蓝图类默认值中配置，运行时蓝图只读。编辑器约束：单位 `s`，最小值 `0.0`，最大值 `30.0`。 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "30.0", Units = "s"))
	float NoiseRevealDurationSeconds = 5.0f;

	/** Full player reveal radius before the boundary wash begins. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "5000.0", Units = "cm"))
	float PerceptionFullRevealRadius = 400.0f;

	/** Radius within which player-revealed surfaces retain their full palette contribution. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "5000.0", Units = "cm"))
	float PerceptionColorFullRadius = 280.0f;

	/** Radius within which player-revealed surfaces retain their full internal normal-edge detail. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "5000.0", Units = "cm"))
	float PerceptionInternalEdgeFullRadius = 340.0f;

	/** Time for a pulse wave to travel from its source to its visual radius. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.001", ClampMax = "30.0", Units = "s"))
	float EchoExpansionSeconds = 0.75f;

	/** Duration of the wet edge generated by the latest pulse. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "30.0", Units = "s"))
	float EchoWetSeconds = 0.20f;

	/** Final residue wash duration. Its start point is derived from ExpireTime. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.001", ClampMax = "30.0", Units = "s"))
	float EchoDryFadeDurationSeconds = 1.30f;

	/** World-space width of the latest wet edge. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "1000.0", Units = "cm"))
	float EchoWaveWidthCm = 12.5f;

	/** Maximum movement allowed when a looping source refreshes its previous spatial slot. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "1000.0", Units = "cm"))
	float EchoRefreshMergeDistanceCm = 25.0f;

	/** Amount of world-space wash noise allowed inside the player reveal feather band. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "1000.0", Units = "cm"))
	float PerceptionBoundaryNoiseCm = 18.0f;

	/** Initial interval for looping ambient perception sources. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.001", ClampMax = "60.0", Units = "s"))
	float DefaultLoopIntervalSeconds = 3.0f;

	/** Depth comparison tolerance for Stencil 3 visible-accent gating. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "100.0", Units = "cm"))
	float AccentDepthToleranceCm = 3.0f;

	/** Perception post-process transition duration. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "5.0", Units = "s"))
	float PerceptionEnterBlendSeconds = 0.30f;

	/** Perception post-process exit transition duration. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception", meta = (ClampMin = "0.0", ClampMax = "5.0", Units = "s"))
	float PerceptionExitBlendSeconds = 0.20f;

	/** Post-process master material, loaded when the player enters Perception. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception|Assets")
	TSoftObjectPtr<UMaterialInterface> PerceptionCompositeMaterial;

	/** MPC_LR_VisualStyle, written by the Perception presentation component. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception|Assets")
	TObjectPtr<UMaterialParameterCollection> PerceptionVisualStyleParameterCollection;

	/** MPC_LR_PerceptionRuntime, written by the Perception presentation component. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception|Assets")
	TObjectPtr<UMaterialParameterCollection> PerceptionRuntimeParameterCollection;

	/** Optional decorative pulse system; its absence never disables rule-driven reveal. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception|Assets")
	TSoftObjectPtr<UNiagaraSystem> PerceptionPulseSystem;

	/** Shared cyan state color written to MPC_LR_VisualStyle for Stencil 2 player occlusion. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Perception")
	FLinearColor PlayerOcclusionStateColor = FLinearColor(0.35f, 0.85f, 1.0f, 1.0f);

	/** Visual style values for the eye overlay; gameplay timing remains in StateTuning. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Eye Overlay")
	FLRStateEyeOverlayStyle PerceptionEyeOverlayStyle;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Eye Overlay")
	FLRStateEyeOverlayStyle CourageEyeOverlayStyle;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Eye Overlay")
	FLRStateEyeOverlayStyle MemoryEyeOverlayStyle;

	/** UI-only success tail; it must fit inside the state presentation window. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Eye Overlay", meta = (ClampMin = "0.0", ClampMax = "1.0", Units = "s"))
	float EyeOverlaySuccessTailSeconds = 0.12f;

	/** Maximum UI-only cancel/reject reverse duration. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Eye Overlay", meta = (ClampMin = "0.0", ClampMax = "1.0", Units = "s"))
	float EyeOverlayCancelSeconds = 0.15f;

	/** Visual open-eye progress at the gameplay threshold; it does not alter gameplay timing. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Eye Overlay", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float EyeOpenThresholdVisualProgress = 0.90f;

	/** Perception Blend Weight 的领域数据，由所属类型负责维护和校验。 C++ 安全默认值为 `1.0f`。 可在 DataAsset 或蓝图类默认值中配置，运行时蓝图只读。编辑器约束：最小值 `0.0`，最大值 `1.0`。 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|PostProcess", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float PerceptionBlendWeight = 1.0f;

	/** Courage Blend Weight 的领域数据，由所属类型负责维护和校验。 C++ 安全默认值为 `1.0f`。 可在 DataAsset 或蓝图类默认值中配置，运行时蓝图只读。编辑器约束：最小值 `0.0`，最大值 `1.0`。 */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|PostProcess", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float CourageBlendWeight = 1.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Transition", meta = (ClampMin = "0.0", ClampMax = "2.0", Units = "s"))
	float CutawayHideDurationSeconds = 0.25f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Transition", meta = (ClampMin = "0.0", ClampMax = "2.0", Units = "s"))
	float CutawayRestoreDurationSeconds = 0.35f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Local", meta = (ClampMin = "32.0", ClampMax = "600.0"))
	float CutawayRadiusRefPx = 200.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Detection", meta = (ClampMin = "1.0", ClampMax = "60.0", Units = "Hz"))
	float CutawayDetectionFrequencyHz = 10.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Detection", meta = (ClampMin = "0.0", ClampMax = "100.0", Units = "cm"))
	float CutawayTraceSphereRadiusCm = 20.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Camera", meta = (ClampMin = "300.0", ClampMax = "1400.0", Units = "cm"))
	float DefaultCameraDistanceCm = 700.0f;

	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Camera", meta = (ClampMin = "0.0", ClampMax = "5.0", Units = "s"))
	float DefaultCameraDistanceBlendSeconds = 0.25f;

	/** Global stencil-2 player occlusion silhouette, authored as After DOF priority 20. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Silhouette")
	TSoftObjectPtr<UMaterialInterface> PlayerOcclusionPostProcessMaterial;

	/** Hard reference to the shared per-camera cutaway state collection used by outline suppression. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Materials")
	TObjectPtr<UMaterialParameterCollection> CutawayViewParameterCollection;

	/** Final validation accepts only instances resolving to these production masters. */
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Presentation|Cutaway|Materials")
	TArray<TSoftObjectPtr<UMaterialInterface>> ApprovedCutawayMasterMaterials;

	/**
	 * @brief 校验当前资产的必填引用、数值边界及跨字段关系，并输出可诊断错误。
	 * @param outError 输出校验失败原因；成功时保持为空。
	 * @return 返回查询值、结构化结果或操作是否成功；失败语义由返回类型定义。
	 */
	virtual bool Validate(FString& outError) const override;
};
